databases:
  - name: postgres
    ipAllowList: []
    databaseName: test_rails_pg_app
    user: test_rails_pg_app

services:
  - type: web
    name: test_rails_pg_app
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false